version: '3.9'
services:
  frontend:
      container_name: app_frontend
      build: ./frontend
      ports:
        - 3000:3000
  backend:
    container_name: backendapi
    build: ./backend
    ports:
      - 3001:3001
    
    environment:
      - PORT=3001
      - DB_USER=root
      - DB_PASS=@12345Db
      - DB_HOST=postgredb
      - DB_NAME=users_testapp_db
      - DB_PORT=5432
    
  db:
    image: postgres:14
    container_name: postgredb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_DB=users_testapp_db
      - POSTGRES_PASSWORD=@12345Db
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: 'always'
   